stages:
  - analysis
  - test
  - build

# region Analysis

detekt:
  stage: analysis
  tags:
    - android
  only:
    - branches
    - merge_requests
  script:
    - ./gradlew detekt
  artifacts:
    when: always
    paths:
      - build/reports/detekt/detekt.html

lintDebug:
  stage: analysis
  tags:
    - android
  only:
    - develop
    - merge_requests
  script:
    - ./gradlew lintPosDebug lintWalletDebug

lintRelease:
  stage: analysis
  tags:
    - android
  only:
    - master
    - /release\/.+/
  script:
    - ./gradlew lintPosRelease lintWalletRelease

# endregion

# region Test

unitTest:
  stage: test
  tags:
    - android
  only:
    - master
    - develop
    - merge_requests
  script:
    - ./gradlew test

androidTest:
  stage: test
  tags:
    - android-test
  only:
    - master
    - develop
    - merge_requests
  script:
    - ./gradlew connectedAndroidTest

# endregion

# region Build

assembleDebug:
  stage: build
  tags:
    - android
  only:
    - develop
    - merge_requests
  script:
    - ./gradlew assembleDebug

assembleRelease:
  stage: build
  tags:
    - android
  only:
    - master
    - /release\/.+/
  script:
    - ./gradlew assembleRelease

# endregion
