stages:
  - test
  - build

# region Test

unitTest:
  stage: test
  tags:
    - android
  only:
    - master
    - develop
    - merge_requests
  script:
    - ./gradlew test

androidTest:
  stage: test
  tags:
    - android-test
  only:
    - master
    - develop
    - merge_requests
  script:
    - ./gradlew connectedAndroidTest

# endregion

# region Build

assembleDebug:
  stage: build
  tags:
    - android
  only:
    - develop
    - merge_requests
  script:
    - ./gradlew assembleDebug

assembleRelease:
  stage: build
  tags:
    - android
  only:
    - master
    - /release\/.+/
  script:
    - ./gradlew assembleRelease

# endregion
